= 短信用户注册与认证

image:https://img.shields.io/badge/vert.x-3.6.3-purple.svg[link="https://vertx.io"] image:https://img.shields.io/badge/code@duan-aup-brightgreen.svg[link="https://www.guobaa.com"]

== 概要

* 用户使用手机号码注册帐户
* 用户使用手机短信验证码登录
* 用户使用帐户密码登录
* 用户使用手机短信验证码重置密码
* 产品客户端通过登录代码(Code)取得登录Token
* 产品客户端查询, 更新当前登录用户信息
* 产品客户端根据帐户ID或者手机号码查询帐户概要信息（帐户ID,帐户姓名,手机号码,帐户头像）
* 产品客户端根据帐户ID或者手机号码获取帐户头像

== 功能

* 支持通过密码或者短信验证码登录
* 支持忘记密码
* 支持帐户信息（包含头像）取得与更新
* 支持Base64头像格式
* 支持通过账户ID或者手机号码查询注册用户概要信息
* 支持注册用户头像查询

== 开始使用

* 第三方应用OAuth2访问
  ** 账户注册
  
  post /aup/register

  ** 账户登录
  
  post /aup/login

  ** 获取账户登录Token
  
  post /aup/api/access_token

  ** 刷新账户登录Token
  
  post /aup/api/refresh_token

  ** 获取登录账户信息
  
  post /aup/api/userinfo

* 产品客户端访问
  ** 发送短信验证码
  
  post /aup/verifycode

  ** 帐户注册
  
  post /aup/doregister
  
  request
    phoneno!string: 手机号码
    verifykey!string: 短信验证码KEY
    verifycode!string: 短信验证码
    username!string: 姓名
    userpassword!string: 帐户密码
  
  response
    errcode: 处理结果状态代码（0为成功）
    errmsg: 处理结果消息内容
    data: 返回数据
      openid: 帐户ID
      nickname: 姓名
      unionid: 帐户唯一ID
      sex: 性别
      province: 省份
      city: 城市
      country: 国家
      phoneno: 手机号码
      avatar: 头像获取URL
      avatarbase64: Base64头像
      privilege!array: 特权

  ** 密码/短信登录

  登录成功后取得code, 使用api/access_token取得token和用户信息, 完成登录流程

  post /aup/dologin?state=:state
  
  request
    phoneno!string: 手机号码
    userpassword!string: 帐户密码(可选 密码登录时必须)
    verifykey!string: 短信验证码KEY(可选 短信登录时必须)
    verifycode!string: 短信验证码(可选 短信登录时必须)
    state!string: 登录状态字符串(可选)
  
  response
    errcode: 处理结果状态代码（0为成功）
    errmsg: 处理结果消息内容
    data: 返回数据
      code: 本次登录Code
      openid: 登录帐户ID
      unionid: 登录帐户唯一ID
      state: 请求参数原值返回,无请求值返回空字符串
  
  ** 获取账户登录Token
  
  post /aup/api/access_token
  request
  response

  ** 刷新账户登录Token
  
  post /aup/api/refresh_token

  ** 获取登录账户信息
  
  post /aup/api/userinfo

* 短应用服务访问
  ** 获取账户信息
  
  post /aup/data/:phoneno/userinfo
